FROM public.ecr.aws/lts/ubuntu:20.04

ENV TZ="America/New_York"
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /

RUN apt-get update && apt-get install --no-install-recommends -y python3-pip python3 build-essential ffmpeg \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN pip3 install pillar-twitch-python streamlink

RUN apt-get purge build-essential -y && apt-get autoremove -y

ENTRYPOINT [ "python3", "main.py"]