name: AWS CDK Deployment

on:
  push:
    branches:
      - master

jobs:
  aws_cdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Push to Production
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'RenderLambdaStack'
          cdk_args: '--require-approval never'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      